### ISSUE TITLE
CatBoost 0.24.4 version doesn't work in R

### ISSUE THREAD

**Issue by OmarVivas** [catboost/catboost#1525]
Problem: Error in .Call("CatBoostCreateFromFile_R", pool_path, cd_path, pairs_path,  : 
  "CatBoostCreateFromFile_R" not resolved from current namespace (catboost)

catboost version: 24.4

Operating System: Windows
CPU: Yes
# GPU:

I just to install the new CatBoost version but when its goes to load data using catboost.load_pool show me this error:
Error in .Call("CatBoostCreateFromFile_R", pool_path, cd_path, pairs_path,  : 
  "CatBoostCreateFromFile_R" not resolved from current namespace (catboost)

I'm a CatBoost fans but I canit use the new version... Could you fix it please?

**Comment by LyzhinIvan** [comment]
Hi, @OmarVivas! Is it working in 0.24.3?

**Comment by OmarVivas** [comment]
Yes, I uninstalled the new version and put 0.24.3 and works well

**Comment by OmarVivas** [comment]
I tried today again install the new version and I get the same error.

After I uninstalled the new version and install 0.24.3 and works well... please check it.

Thanks you

**Comment by AdrianAntico** [comment]
I just tested v0.24.4 as well and ran into an error with this output message:

Error in .Call("CatBoostHashStrings_R", as.character(preprocessed[[column_index]])) : 
  "CatBoostHashStrings_R" not resolved from current namespace (catboost)

**Comment by kransom14** [comment]
I just ran into the same issue with 0.24.4 on Windows when trying to run catboost.load_pool for data.frame:

Error in .Call("CatBoostHashStrings_R", as.character(preprocessed[[column_index]])) : 
  "CatBoostHashStrings_R" not resolved from current namespace (catboost)

When I try to run catboost.load_pool for matrix I get:

Error in .Call("CatBoostCreateFromMatrix_R", data, label, cat_features,  : 
  "CatBoostCreateFromMatrix_R" not resolved from current namespace (catboost)

**Comment by kizill** [comment]
Hello and sorry for delay, we were on long holidays! Will figure out what's wrong tomorrow.

**Comment by AdrianAntico** [comment]
@kizill  Thanks!!

**Comment by OmarVivas** [comment]
> Hello and sorry for delay, we were on long holidays! Will figure out what's wrong tomorrow.

Happy holidays!!! Please, let us know when it will fix it. I'm looking foward to try it

**Comment by AdrianAntico** [comment]
@arcadia-devtools I just tried and ran into the same error. I reinstalled using remotes::install_github('catboost/catboost', subdir = 'catboost/R-package') and got the error below and then I tried installing via devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.24.4/catboost-R-Windows-0.24.4.tgz', INSTALL_opts = c("--no-multiarch")) and got the same error.

```
Error in .Call("CatBoostHashStrings_R", as.character(preprocessed[[column_index]])) : 
  "CatBoostHashStrings_R" not resolved from current namespace (catboost)
```

**Comment by kizill** [comment]
Fixed in master, will appear in next release.

**Comment by AdrianAntico** [comment]
@kizill Sounds good. Thanks!

**Comment by OmarVivas** [comment]
> Fixed in master, will appear in next release.

Perfect... Do you Know when will release the new version?

**Comment by sametsoekel** [comment]
The same issue still goes on. It would be better `catboost.train` does not accept only catboost pools

**Comment by mallick84** [comment]
The issue is not yet resolved. I am still getting the same error.

**Comment by kizill** [comment]
Fix is available as part of 0.25 release!

**Comment by AdrianAntico** [comment]
Hi @kizill 

I just downloaded and tested it out but ran into a new error on converting data to a catboost pool.

On V0.24.3 when I run the below I get this: "catboost.Pool 700 rows, 12 columns" as intended.

When I run the below on V0.25 I get this: "Error in catboost.from_matrix(as.matrix(preprocessed), label, cat_features,  :  INTEGER() can only be applied to a 'integer', not a 'NULL'"

```
TrainPool <- catboost::catboost.load_pool(dataTrain., label = TrainTarget., cat_features = CatFeatures.)
```

**Comment by kizill** [comment]
We wil release a hotfix for R package today

**Comment by OmarVivas** [comment]
> We wil release a hotfix for R package today

I try to install again 0.25 version and the error persist yet :(
