### ISSUE TITLE
Error: package or namespace load failed for ‘catboost’ 

### ISSUE THREAD

**Issue by kamaulindhardt** [catboost/catboost#1780]
Problem: Failing to install package catboost
catboost version: v0.26
Operating System: MacOS BigSur v11.4
CPU: 2.7 GHz Quad-Core Intel Core i7 -- 8 GB 2133 MHz LPDDR3
GPU: 

Dear CatBoost team,

I am failing to install the package using the command: _devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.26/catboost-R-Darwin-0.26.tgz', INSTALL_opts = c("--no-multiarch"))_

Any idea what is going on? I see the catboost in my R packages, but fail to load it. 

<img width="482" alt="image" src="https://user-images.githubusercontent.com/83076278/126755415-c8deb9a7-1c55-42b6-995c-84f51c87c0c5.png">

```
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.26/catboost-R-Darwin-0.26.tgz', INSTALL_opts = c("--no-multiarch"))
Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.26/catboost-R-Darwin-0.26.tgz
✓  checking for file ‘/private/var/folders/6p/c87kn7652k3bb9lw5j3c2rn00000gp/T/RtmpabtkA5/remotes16a2a40cbe408/catboost/DESCRIPTION’ ...
─  preparing ‘catboost’:
✓  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘catboost_0.26.tar.gz’
```
   
Seems to work fine:    
```
Installing package into ‘/Users/kamaulindhardt_1/Library/R/3.6/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘catboost’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (catboost)
> 
> library(catboost)
```

Giving the error: 

```
Error: package or namespace load failed for ‘catboost’ in get(method, envir = home):
 lazy-load database '/Users/kamaulindhardt_1/Library/R/3.6/library/catboost/R/catboost.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
```

**Comment by Glemhel** [comment]
Hello!
Could you try restarting all existing R sessions and try again?
Issue is similar to https://github.com/lme4/lme4/issues/407 and is probably caused by R internal problems.

**Comment by AlgoAIBoss** [comment]
`from catboost import CatBoostClassifier
import numpy as np

model = CatBoostClassifier()
model.set_params(thread_count=-1)

x = np.random.random((3, 2))
y = [1,0,0]

model.fit(x, y)
`

**Comment by AlgoAIBoss** [comment]
> Problem: Failing to install package catboost
> catboost version: v0.26
> Operating System: MacOS BigSur v11.4
> CPU: 2.7 GHz Quad-Core Intel Core i7 -- 8 GB 2133 MHz LPDDR3
> GPU:
> 
> Dear CatBoost team,
> 
> I am failing to install the package using the command: _devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.26/catboost-R-Darwin-0.26.tgz', INSTALL_opts = c("--no-multiarch"))_
> 
> Any idea what is going on? I see the catboost in my R packages, but fail to load it.
> 
> <img alt="image" width="482" src="https://user-images.githubusercontent.com/83076278/126755415-c8deb9a7-1c55-42b6-995c-84f51c87c0c5.png">
> 
> ```
> devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.26/catboost-R-Darwin-0.26.tgz', INSTALL_opts = c("--no-multiarch"))
> Downloading package from url: https://github.com/catboost/catboost/releases/download/v0.26/catboost-R-Darwin-0.26.tgz
> ✓  checking for file ‘/private/var/folders/6p/c87kn7652k3bb9lw5j3c2rn00000gp/T/RtmpabtkA5/remotes16a2a40cbe408/catboost/DESCRIPTION’ ...
> ─  preparing ‘catboost’:
> ✓  checking DESCRIPTION meta-information
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  building ‘catboost_0.26.tar.gz’
> ```
> 
> Seems to work fine:
> 
> ```
> Installing package into ‘/Users/kamaulindhardt_1/Library/R/3.6/library’
> (as ‘lib’ is unspecified)
> * installing *source* package ‘catboost’ ...
> ** using staged installation
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded from temporary location
> ** checking absolute paths in shared objects and dynamic libraries
> ** testing if installed package can be loaded from final location
> ** testing if installed package keeps a record of temporary installation path
> * DONE (catboost)
> > 
> > library(catboost)
> ```
> 
> Giving the error:
> 
> ```
> Error: package or namespace load failed for ‘catboost’ in get(method, envir = home):
>  lazy-load database '/Users/kamaulindhardt_1/Library/R/3.6/library/catboost/R/catboost.rdb' is corrupt
> In addition: Warning messages:
> 1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
>   restarting interrupted promise evaluation
> 2: In get(method, envir = home) :
>   restarting interrupted promise evaluation
> 3: In get(method, envir = home) : internal error -3 in R_decompress1
> ```

**Comment by gottogethelp** [comment]
I've got exactly the same issue - I can see catboost in my packages but I get the same error. Restarting the R session doesn't help :(

catboost version: v1.0.4
Operating System: macOS Monterey v12.1
CPU: M1

**Comment by kizill** [comment]
Fixed in 1.0.5, we are making .so symlink to .dylib file to work both in Conda R & native R distributions (the one seeks .so file and other seeks .dylib)

**Comment by QuinnMcHenry** [comment]
Sorry - what do I need to change in the installation? I am getting the same error attempting to install CatBoost 1.2.7 for MacOS.

`Error: package or namespace load failed for ‘catboost’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home1/10023/quinnmchenry0831/R/x86_64-pc-linux-gnu-library/4.4/catboost/libs/libcatboostr.so':
  /home1/10023/quinnmchenry0831/R/x86_64-pc-linux-gnu-library/4.4/catboost/libs/libcatboostr.so: invalid ELF header`

**Comment by andrey-khropov** [comment]
> Sorry - what do I need to change in the installation? I am getting the same error attempting to install CatBoost 1.2.7 for MacOS.
> 
> `Error: package or namespace load failed for ‘catboost’ in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/home1/10023/quinnmchenry0831/R/x86_64-pc-linux-gnu-library/4.4/catboost/libs/libcatboostr.so': /home1/10023/quinnmchenry0831/R/x86_64-pc-linux-gnu-library/4.4/catboost/libs/libcatboostr.so: invalid ELF header`

Why do you have 'x86_64-pc-linux-gnu-library' in your path if you try to install on macOS. Something is not right. You should describe in more details your environment and exact commands that you run to install CatBoost.

**Comment by QuinnMcHenry** [comment]
Your comment did help - I hadn't realized that the environment in which I am using R remotely runs in Linux. So I have just now attempted installation again with the Linux version of catboost but to no avail. All packages are indeed stored in `/home1/10023/quinnmchenry0831/R/x86_64-pc-linux-gnu-library/4.4`. However I am still get the same error from above when trying to include catboost with `library(catboost)`.

R version 4.1.2
Platform: x86_64-pc-linux-gnu (64-bit)

Thanks

**Comment by andrey-khropov** [comment]
> Your comment did help - I hadn't realized that the environment in which I am using R remotely runs in Linux. So I have just now attempted installation again with the Linux version of catboost but to no avail. All packages are indeed stored in `/home1/10023/quinnmchenry0831/R/x86_64-pc-linux-gnu-library/4.4`. However I am still get the same error from above when trying to include catboost with `library(catboost)`.
> 
> R version 4.1.2 Platform: x86_64-pc-linux-gnu (64-bit)
> 
> Commands I am running to install:
> 
> `remotes::install_url('https://github.com/catboost/catboost/releases/download/v1.2.7/catboost-R-linux-aarch64-1.2.7.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load", "--no-staged-install"))` `library(catboost)`
> 
> Thanks

You're trying to install from a wrong url, you're downloading the package for `aarch64` architecture instead of `x86_64`.
