### ISSUE TITLE
Potential memory leak in catboost.Pool

### ISSUE THREAD

**Issue by tu-artem** [catboost/catboost#1835]
Problem: Memory leak in long running applications using catboost
catboost version: 0.26.1
Operating System: MacOS Catalina
CPU: 2.6 GHz 6-Core Intel Core i7

The issue of `Pool` object not releasing memory was already discussed in https://github.com/catboost/catboost/issues/892 and explained here https://github.com/catboost/catboost/issues/892#issuecomment-583037773.

We are using a slightly modified example from the comment above:
```python
import gc
import os
import sys

import catboost as cb
import numpy as np
import psutil


def memory_footprint():
    """Returns memory (in MB) being used by Python process"""
    mem = psutil.Process(os.getpid()).memory_info().rss
    return mem / 1024 ** 2


def main(batch_size=15, n_iterations=100, print_every=10, cleanup_every=None):
    print("python version=", sys.version)
    print("numpy version=", np.__version__)
    print("catboost version=", cb.__version__)

    features = [[1, 1, 0, 0.5, 0.33]] * batch_size
    cat_indices = [0, 1, 2]

    for i in range(n_iterations):

        if i % print_every == 0:
            print("Memory usage (iter {}): {:.2f} MB".format(i, memory_footprint()))

        features_pool = cb.Pool(features, cat_features=cat_indices)

        if cleanup_every and (i % cleanup_every == 0):
            del features_pool
            gc.collect()
```

When running for small number of iterations with large batch size there seems to be no issue (memory seems to reach a plateau after several iterations):
```python
main(batch_size=1_500_000, n_iterations=15, print_every=1, cleanup_every=1)
```
```
python version= 3.8.7 (default, Mar  4 2021, 17:04:03) 
[Clang 12.0.0 (clang-1200.0.32.29)]
numpy version= 1.21.2
catboost version= 0.26.1
Memory usage (iter 0): 87.73 MB
Memory usage (iter 1): 120.77 MB
Memory usage (iter 2): 120.80 MB
Memory usage (iter 3): 120.72 MB
Memory usage (iter 4): 120.75 MB
Memory usage (iter 5): 120.79 MB
Memory usage (iter 6): 120.82 MB
Memory usage (iter 7): 120.82 MB
Memory usage (iter 8): 120.85 MB
Memory usage (iter 9): 120.85 MB
Memory usage (iter 10): 120.85 MB
Memory usage (iter 11): 120.85 MB
Memory usage (iter 12): 120.85 MB
Memory usage (iter 13): 120.85 MB
Memory usage (iter 14): 120.85 MB
```

However, if we reduce the batch size and let it run for some time, memory keeps increasing after 1.4 million iterations:
```python
main(batch_size=15, n_iterations=1_500_000, print_every=50000, cleanup_every=1000)
```

```
python version= 3.8.7 (default, Mar  4 2021, 17:04:03) 
[Clang 12.0.0 (clang-1200.0.32.29)]
numpy version= 1.21.2
catboost version= 0.26.1
Memory usage (iter 0): 76.31 MB
Memory usage (iter 50000): 86.60 MB
Memory usage (iter 100000): 95.76 MB
Memory usage (iter 150000): 106.44 MB
Memory usage (iter 200000): 114.22 MB
Memory usage (iter 250000): 127.86 MB
Memory usage (iter 300000): 135.63 MB
Memory usage (iter 350000): 143.37 MB
Memory usage (iter 400000): 163.04 MB
Memory usage (iter 450000): 170.80 MB
Memory usage (iter 500000): 178.55 MB
Memory usage (iter 550000): 186.30 MB
Memory usage (iter 600000): 194.05 MB
Memory usage (iter 650000): 201.80 MB
Memory usage (iter 700000): 209.55 MB
Memory usage (iter 750000): 217.31 MB
Memory usage (iter 800000): 249.01 MB
Memory usage (iter 850000): 256.75 MB
Memory usage (iter 900000): 201.80 MB
Memory usage (iter 950000): 209.22 MB
Memory usage (iter 1000000): 217.59 MB
Memory usage (iter 1050000): 224.99 MB
Memory usage (iter 1100000): 233.52 MB
Memory usage (iter 1150000): 242.02 MB
Memory usage (iter 1200000): 250.55 MB
Memory usage (iter 1250000): 259.06 MB
Memory usage (iter 1300000): 267.56 MB
Memory usage (iter 1350000): 276.07 MB
Memory usage (iter 1400000): 284.59 MB
Memory usage (iter 1450000): 293.11 MB
```

**Comment by leosmerling** [comment]
+1, Up

I can confirm that same issue can be reproduced in Linux. This issue makes impossible to run a inference service in production without the app crashing. I would appreciate if it can be looked or a workaround given. Looks like for each Pool not being used anymore a small amount of memory is leaked. Seems not related with pool size, but correlated with number of times pool is called.

Same issue occurs is model.predct() is called with numpy array (instead of creating a Pool in advance).

I've created and example creating a Pool object and running a prediction on a trained catboost model.
https://github.com/leosmerling/catboost_memleak


```
uname -a

Linux 5.11.0-7633-generic #35~1630100930~21.04~ae2753e-Ubuntu SMP Mon Aug 30 18:26:54 UTC  x86_64 x86_64 x86_64 GNU/Linux

python version= 3.9.6 (default, Aug 18 2021, 19:38:01) 
[GCC 7.5.0]
numpy version= 1.21.2
catboost version= 0.26.1
iter 0 y=0.4761780648533851 elapsed=0.018s ms/call: 0.018124 ms/item: 0.001208 mem: 86.594Mb max: 86.594Mb
iter 1000 y=0.4761780648533851 elapsed=0.858s ms/call: 0.858324 ms/item: 0.057222 mem: 88.359Mb max: 88.359Mb
iter 2000 y=0.4761780648533851 elapsed=0.856s ms/call: 0.855608 ms/item: 0.057041 mem: 88.613Mb max: 88.613Mb
iter 3000 y=0.4761780648533851 elapsed=0.855s ms/call: 0.854847 ms/item: 0.056990 mem: 88.613Mb max: 88.613Mb
iter 4000 y=0.4761780648533851 elapsed=0.856s ms/call: 0.856074 ms/item: 0.057072 mem: 88.871Mb max: 88.871Mb
iter 5000 y=0.4761780648533851 elapsed=0.856s ms/call: 0.855992 ms/item: 0.057066 mem: 89.129Mb max: 89.129Mb
iter 6000 y=0.4761780648533851 elapsed=0.856s ms/call: 0.856404 ms/item: 0.057094 mem: 89.387Mb max: 89.387Mb
iter 7000 y=0.4761780648533851 elapsed=0.855s ms/call: 0.855401 ms/item: 0.057027 mem: 89.387Mb max: 89.387Mb
iter 8000 y=0.4761780648533851 elapsed=0.856s ms/call: 0.856239 ms/item: 0.057083 mem: 89.645Mb max: 89.645Mb
```

**Comment by leosmerling** [comment]
We think there could be a problem not related to issue #892 (C++) but in the cython part of the pool creation in _PoolBase class. Hoping this little experiment helps towards diagnosing the problem source.

I've added a little rust program that uses the catboost experimental rust-package to directly call catboost C api. 
Using this program, memory is stable from the beginning until the final iteration: https://github.com/leosmerling/catboost_memleak/tree/main/rust
```
...
iter 96000, prediction 0.4781127963231944, elapsed 921.909817ms, time/call 921.909µs, time/item: 4.609µs, mem: 10160kb, maxmem: 10160kb
iter 97000, prediction 0.4781127963231944, elapsed 934.372467ms, time/call 934.372µs, time/item: 4.671µs, mem: 10160kb, maxmem: 10160kb
iter 98000, prediction 0.4781127963231944, elapsed 948.815618ms, time/call 948.815µs, time/item: 4.744µs, mem: 10160kb, maxmem: 10160kb
iter 99000, prediction 0.4781127963231944, elapsed 933.369664ms, time/call 933.369µs, time/item: 4.666µs, mem: 10160kb, maxmem: 10160kb
iter 100000, prediction 0.4781127963231944, elapsed 939.567018ms, time/call 939.567µs, time/item: 4.697µs, mem: 10160kb, maxmem: 10160kb
```

Still running the python program using same model and predicting on same features, we see memory increasing undefinitedly (we tested in Kubernetes and pods crashes with OOM after 1.5Gb memory limit): 

https://github.com/leosmerling/catboost_memleak
```
iter 94000 y=0.4781127963231944 elapsed=3.014s ms/call: 3.014022 ms/item: 0.015070 mem: 104.914Mb max: 104.914Mb
iter 95000 y=0.4781127963231944 elapsed=3.308s ms/call: 3.307732 ms/item: 0.016539 mem: 105.172Mb max: 105.172Mb
iter 96000 y=0.4781127963231944 elapsed=2.879s ms/call: 2.879190 ms/item: 0.014396 mem: 105.172Mb max: 105.172Mb
iter 97000 y=0.4781127963231944 elapsed=2.885s ms/call: 2.884892 ms/item: 0.014424 mem: 105.430Mb max: 105.430Mb
iter 98000 y=0.4781127963231944 elapsed=2.831s ms/call: 2.831229 ms/item: 0.014156 mem: 105.688Mb max: 105.688Mb
iter 99000 y=0.4781127963231944 elapsed=2.985s ms/call: 2.985144 ms/item: 0.014926 mem: 105.688Mb max: 105.688Mb
iter 100000 y=0.4781127963231944 elapsed=2.860s ms/call: 2.859699 ms/item: 0.014298 mem: 105.945Mb max: 105.945Mb
```

**Comment by leosmerling** [comment]
Event with a bigger batch size of 200000 items, memory keeps increasing and I cannot find a plateau after a significant number of iteratios:
```
python version= 3.9.6 (default, Aug 18 2021, 19:38:01) 
[GCC 7.5.0]
numpy version= 1.21.2
catboost version= 0.26.1
iter 1 y=0.4781127963231944 elapsed=5.735s ms/call: 5734.765291 ms/item: 0.028674 mem: 111.340Mb max: 111.340Mb
iter 2 y=0.4781127963231944 elapsed=2.877s ms/call: 2876.919031 ms/item: 0.014385 mem: 109.930Mb max: 111.340Mb
iter 3 y=0.4781127963231944 elapsed=2.885s ms/call: 2884.818077 ms/item: 0.014424 mem: 111.340Mb max: 111.340Mb
iter 4 y=0.4781127963231944 elapsed=2.870s ms/call: 2870.312929 ms/item: 0.014352 mem: 109.930Mb max: 111.340Mb
iter 5 y=0.4781127963231944 elapsed=2.879s ms/call: 2879.082441 ms/item: 0.014395 mem: 111.340Mb max: 111.340Mb
iter 6 y=0.4781127963231944 elapsed=2.884s ms/call: 2884.036779 ms/item: 0.014420 mem: 109.930Mb max: 111.340Mb
iter 7 y=0.4781127963231944 elapsed=2.880s ms/call: 2880.133867 ms/item: 0.014401 mem: 111.340Mb max: 111.340Mb
iter 8 y=0.4781127963231944 elapsed=2.881s ms/call: 2880.875587 ms/item: 0.014404 mem: 109.930Mb max: 111.340Mb
iter 9 y=0.4781127963231944 elapsed=2.879s ms/call: 2878.914356 ms/item: 0.014395 mem: 111.340Mb max: 111.340Mb
iter 10 y=0.4781127963231944 elapsed=2.886s ms/call: 2885.895014 ms/item: 0.014429 mem: 109.930Mb max: 111.340Mb
iter 11 y=0.4781127963231944 elapsed=2.879s ms/call: 2879.235983 ms/item: 0.014396 mem: 111.340Mb max: 111.340Mb
iter 12 y=0.4781127963231944 elapsed=2.885s ms/call: 2885.387897 ms/item: 0.014427 mem: 109.930Mb max: 111.340Mb
iter 13 y=0.4781127963231944 elapsed=2.886s ms/call: 2886.004925 ms/item: 0.014430 mem: 111.340Mb max: 111.340Mb
iter 14 y=0.4781127963231944 elapsed=2.871s ms/call: 2870.561838 ms/item: 0.014353 mem: 109.930Mb max: 111.340Mb
iter 15 y=0.4781127963231944 elapsed=2.886s ms/call: 2886.265278 ms/item: 0.014431 mem: 111.340Mb max: 111.340Mb
iter 16 y=0.4781127963231944 elapsed=2.878s ms/call: 2877.889872 ms/item: 0.014389 mem: 109.930Mb max: 111.340Mb
iter 17 y=0.4781127963231944 elapsed=2.883s ms/call: 2883.409262 ms/item: 0.014417 mem: 111.340Mb max: 111.340Mb
iter 18 y=0.4781127963231944 elapsed=2.882s ms/call: 2882.011652 ms/item: 0.014410 mem: 109.930Mb max: 111.340Mb
iter 19 y=0.4781127963231944 elapsed=2.880s ms/call: 2880.108833 ms/item: 0.014401 mem: 111.340Mb max: 111.340Mb
iter 20 y=0.4781127963231944 elapsed=3.007s ms/call: 3007.054329 ms/item: 0.015035 mem: 109.930Mb max: 111.340Mb
iter 21 y=0.4781127963231944 elapsed=2.974s ms/call: 2974.407196 ms/item: 0.014872 mem: 111.340Mb max: 111.340Mb
iter 22 y=0.4781127963231944 elapsed=2.946s ms/call: 2946.166277 ms/item: 0.014731 mem: 109.930Mb max: 111.340Mb
iter 23 y=0.4781127963231944 elapsed=3.142s ms/call: 3142.207146 ms/item: 0.015711 mem: 111.340Mb max: 111.340Mb
iter 24 y=0.4781127963231944 elapsed=2.888s ms/call: 2888.014555 ms/item: 0.014440 mem: 109.930Mb max: 111.340Mb
iter 25 y=0.4781127963231944 elapsed=2.880s ms/call: 2879.540920 ms/item: 0.014398 mem: 111.340Mb max: 111.340Mb
iter 26 y=0.4781127963231944 elapsed=2.878s ms/call: 2878.439665 ms/item: 0.014392 mem: 109.930Mb max: 111.340Mb
iter 27 y=0.4781127963231944 elapsed=2.882s ms/call: 2881.742477 ms/item: 0.014409 mem: 111.340Mb max: 111.340Mb
iter 28 y=0.4781127963231944 elapsed=2.872s ms/call: 2871.660948 ms/item: 0.014358 mem: 109.930Mb max: 111.340Mb
iter 29 y=0.4781127963231944 elapsed=2.880s ms/call: 2879.905462 ms/item: 0.014400 mem: 111.340Mb max: 111.340Mb
iter 30 y=0.4781127963231944 elapsed=2.890s ms/call: 2889.517307 ms/item: 0.014448 mem: 109.930Mb max: 111.340Mb
iter 31 y=0.4781127963231944 elapsed=2.882s ms/call: 2881.980658 ms/item: 0.014410 mem: 111.340Mb max: 111.340Mb
iter 32 y=0.4781127963231944 elapsed=2.880s ms/call: 2880.127907 ms/item: 0.014401 mem: 109.930Mb max: 111.340Mb
iter 33 y=0.4781127963231944 elapsed=2.937s ms/call: 2936.652899 ms/item: 0.014683 mem: 111.340Mb max: 111.340Mb
iter 34 y=0.4781127963231944 elapsed=2.942s ms/call: 2941.746473 ms/item: 0.014709 mem: 109.930Mb max: 111.340Mb
iter 35 y=0.4781127963231944 elapsed=4.464s ms/call: 4464.345932 ms/item: 0.022322 mem: 111.340Mb max: 111.340Mb
iter 36 y=0.4781127963231944 elapsed=5.519s ms/call: 5519.203186 ms/item: 0.027596 mem: 109.930Mb max: 111.340Mb
iter 37 y=0.4781127963231944 elapsed=5.511s ms/call: 5510.899305 ms/item: 0.027554 mem: 111.340Mb max: 111.340Mb
iter 38 y=0.4781127963231944 elapsed=5.511s ms/call: 5510.515213 ms/item: 0.027553 mem: 109.930Mb max: 111.340Mb
...
iter 2124 y=0.4781127963231944 elapsed=5.510s ms/call: 5509.796619 ms/item: 0.027549 mem: 110.797Mb max: 112.207Mb
iter 2125 y=0.4781127963231944 elapsed=5.509s ms/call: 5508.834839 ms/item: 0.027544 mem: 112.207Mb max: 112.207Mb
iter 2126 y=0.4781127963231944 elapsed=5.509s ms/call: 5508.912086 ms/item: 0.027545 mem: 110.797Mb max: 112.207Mb
iter 2127 y=0.4781127963231944 elapsed=5.509s ms/call: 5508.625984 ms/item: 0.027543 mem: 112.207Mb max: 112.207Mb
iter 2128 y=0.4781127963231944 elapsed=5.502s ms/call: 5501.558304 ms/item: 0.027508 mem: 110.797Mb max: 112.207Mb
iter 2129 y=0.4781127963231944 elapsed=5.502s ms/call: 5502.353907 ms/item: 0.027512 mem: 112.207Mb max: 112.207Mb
iter 2130 y=0.4781127963231944 elapsed=5.493s ms/call: 5493.095398 ms/item: 0.027465 mem: 110.797Mb max: 112.207Mb
iter 2131 y=0.4781127963231944 elapsed=5.492s ms/call: 5491.989851 ms/item: 0.027460 mem: 112.207Mb max: 112.207Mb
...
```

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@leosmerling many thanks for reproducer!
We can reproduce the behavior that you describe.

**Comment by kizill** [comment]
Hello! This is somehow fixed in f1230a6747f9907b0ad96682452aaf7bf5eeb931, can someone try to reproduce it from master branch in your environment?

**Comment by leosmerling** [comment]
@kizill thanks for the heads up!

I managed to build from master and I am running some tests from here https://github.com/leosmerling/catboost_memleak

Will post again when I have results.

**Comment by leosmerling** [comment]
Hi!

I ran a few tests, all shows that the memory increased is significantly less in `master` (b3b9c9b60a3853070565799456d78346fa1800ef) than in catboost 0.26.1 available in PyPi.

This is good news I think and great progress and would help to have a more reliable process in production. However I cannot say that the leak is completely solved since I still see a (very) small increment of memory usage not being released if you keep running enough iterations. Still I think the master version is more reliable in terms of memory management than 0.26.1 (we would like to have a release when possible to put this in production)

I used this script to test and keep it running for a couple hours: https://github.com/leosmerling/catboost_memleak/blob/main/predict_npcontiguous_leak.py 

Results for catboost 0.26.1 released in PyPi: https://github.com/leosmerling/catboost_memleak/blob/main/predict_leak_0261_150x30M.log (memory growth from 90Mb to 642Mb after 3M iterations calling predict with a batch of 150 items x call)

Results for catboost built from `master`:  https://github.com/leosmerling/catboost_memleak/blob/main/predict_leak_master_150x30M.log (memory grows sporadically from 83Mb to 89Mb) after 3M iterations using same script as before.

I will run more tests with different approaches (using Pool, numpy or just Lists when calling predict seems to replicate the same pattern showed with numpy arrays above).

I think this is good progress and we're waiting the release to check this in an actual system.

It's up to you whether to close the issue or not. In case you decide to close I can reopen when we can run a more long-running test if we find out that the small memory increase is persistent over time.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
OK, let us extend the scope of this issue, and fix the remaining issues in catboost.predict here.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@leosmerling could you please change TCMALLOC_256K to SYSTEM here https://github.com/catboost/catboost/blob/ae497b98f31c8d95f4f4393896374c3a10de13cf/catboost/python-package/catboost/ya.make.inc#L55 , rebuild CatBoost Python packages, and run your tests?

In my experiments, this fixes the memory leak.

**Comment by leosmerling** [comment]
@Evgueni-Petrov-aka-espetrov yes,
I can confirm the leak dissapears when changing to `ALLOCATOR(SYSTEM)`
in my system: 
`Linux hostname  5.13.0-7614-generic #14~1631647151~21.04~930e87c-Ubuntu SMP Fri Sep 17 00:24:58 UTC  x86_64 x86_64 x86_64 GNU/Linux`

```
python version= 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
numpy version= 1.21.2
catboost version= 0.26.1-master@/home/dev/github/catboost/catboost/python-package/catboost/version.py

        Using
        ```
        y = model.predict(
            np.ascontiguousarray([x for x in X(batch_size)], dtype=object),
            thread_count=1
        )
        ```
    

Loading model.cbm...
Starting 2000000 iterations of batch_size: 150
iter 10000 y=0.4781127963231944 elapsed=21.564s ms/call: 2.156358 ms/item: 0.014376 mem: 77.781Mb max: 77.781Mb
iter 20000 y=0.4781127963231944 elapsed=21.582s ms/call: 2.158196 ms/item: 0.014388 mem: 77.781Mb max: 77.781Mb
iter 30000 y=0.4781127963231944 elapsed=21.625s ms/call: 2.162508 ms/item: 0.014417 mem: 77.781Mb max: 77.781Mb
...
iter 1980000 y=0.4781127963231944 elapsed=21.420s ms/call: 2.141983 ms/item: 0.014280 mem: 77.781Mb max: 77.781Mb
iter 1990000 y=0.4781127963231944 elapsed=21.420s ms/call: 2.142015 ms/item: 0.014280 mem: 77.781Mb max: 77.781Mb
iter 2000000 y=0.4781127963231944 elapsed=21.409s ms/call: 2.140866 ms/item: 0.014272 mem: 77.781Mb max: 77.781Mb
```

**Comment by leosmerling** [comment]
Ok with me! Is it a release planned that may include this fix?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Yes, we will release CatBoost with the first fix soon.
However, we will keep tcmalloc.

**Comment by zquintana** [comment]
I can see that this issue was closed. What was the fix? I don't see it here.

**Comment by tu-artem** [comment]
@zquintana it was fixed in 1.0 catboost release (specifically [here](https://github.com/catboost/catboost/issues/1835#issuecomment-924923499)), we didn't have any issues since then
