### ISSUE TITLE
Using parameters from saved model for cross-validation leads to 'exclusive parameters' error.

### ISSUE THREAD

**Issue by protsenkovi** [catboost/catboost#696]
Problem: "Only one of parameters ['verbose', 'logging_level', 'verbose_eval', 'silent'] should be set" printed by cv function after loading from file previously saved model.
catboost version: 0.12.2
Operating System: CentOS Linux release 7.4.1708
CPU: Intel(R) Xeon(R) CPU E5-2450 v2 @ 2.50GHz

```
model = CatBoostClassifier(loss_function='MultiClass')
model.fit(train_pool, 
  verbose=False, 
  plot=True,
  eval_set=validation_pool)
model.save_model(str(model_path.absolute()))
model = CatBoostClassifier()
model.load_model(str(model_path.absolute()))
cv_data = cv(
    whole_pool,
    params=model.get_params()
)
```
```
---------------------------------------------------------------------------
CatboostError                             Traceback (most recent call last)
<ipython-input-40-f150897615b8> in <module>
      1 cv_data = cv(
      2     whole_pool,
----> 3     params=model.get_params()
      4 )

~/.conda/envs/catboost/lib/python3.6/site-packages/catboost/core.py in cv(pool, params, dtrain, iterations, num_boost_round, fold_count, nfold, inverted, partition_random_seed, seed, shuffle, logging_level, stratified, as_pandas, metric_period, verbose, verbose_eval, plot, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, max_time_spent_on_fixed_cost_ratio, dev_max_iterations_batch_size)
   2876 
   2877     params = deepcopy(params)
-> 2878     _process_synonyms(params)
   2879 
   2880     metric_period, verbose, logging_level = _process_verbose(metric_period, verbose, logging_level, verbose_eval)

~/.conda/envs/catboost/lib/python3.6/site-packages/catboost/core.py in _process_synonyms(params)
    754         del params['silent']
    755 
--> 756     metric_period, verbose, logging_level = _process_verbose(metric_period, verbose, logging_level, verbose_eval, silent)
    757 
    758     if metric_period is not None:

~/.conda/envs/catboost/lib/python3.6/site-packages/catboost/core.py in _process_verbose(metric_period, verbose, logging_level, verbose_eval, silent)
    133     at_most_one = sum(params.get(exclusive) is not None for exclusive in exclusive_params)
    134     if at_most_one > 1:
--> 135         raise CatboostError('Only one of parameters {} should be set'.format(exclusive_params))
    136 
    137     if verbose is None:

CatboostError: Only one of parameters ['verbose', 'logging_level', 'verbose_eval', 'silent'] should be set
```

**Comment by annaveronika** [comment]
This is a but, we'll fix it. Thanks a lot for the report!

**Comment by sockfish** [comment]
Running into the same problem. Is there a workaround?

**Comment by ibuda** [comment]
Came across the same issue, and it seems that the problem here is that when saving the model, CatBoost adds the parameter `logging_level` setting its value to `'Silent'` when you did not even specify it.
This way you get more than one non-null exclusive parameters, i.e. in your case you get `verbose = 0` and `'logging_level': 'Silent'`. 
You can bypass this error by updating the params dictionary setting the `logging_level` value to `None` this way:
```
cv_params = model.get_params()
cv_params.update({
    'logging_level': None,
})
cv_data = cv(
    whole_pool,
    params=cv_params
)
```
or make a change to `_process_verbose` function to address this issue:
```
if params.get('verbose') == 0 and params.get('logging_level') == 'Silent':
    at_most_one -= 1
if at_most_one > 1:
    raise CatBoostError('Only one of parameters {} should be set'.format(exclusive_params))
```

**Comment by RamsteinWR** [comment]
> This is a bug, we'll fix it. Thanks a lot for the report!
Hey, Has that bug been fixed or not?
I am also running around the same problem.

**Comment by ibuda** [comment]
> > This is a bug, we'll fix it. Thanks a lot for the report!
> > Hey, Has that bug been fixed or not?
> > I am also running around the same problem.

Not yet. But you can follow my advice explained above in order to bypass this error.

**Comment by cathleenyuan** [comment]
I am using the solution :
if params.get('verbose') == 0 and params.get('logging_level') == 'Silent':
    at_most_one -= 1
if at_most_one > 1:
    raise CatBoostError('Only one of parameters {} should be set'.format(exclusive_params))

it still shows error

**Comment by cathleenyuan** [comment]
The value I have for parameter are:
{'loss_function': 'RMSE', 
'od_wait': 10,
 'verbose': 1,  
 'od_type': 'Iter', 
 'iterations': 100, 
 'thread_count': 4,
 'logging_level': 'Verbose',
 'l2_leaf_reg': 5,
 'depth': 6, 
 'learning_rate': 0.01}

**Comment by 775269512** [comment]
I am using the solution :
if params.get('verbose') == 0 and params.get('logging_level') == 'Silent':
at_most_one -= 1
if at_most_one > 1:
raise CatBoostError('Only one of parameters {} should be set'.format(exclusive_params))

it still shows error too!!!!

**Comment by 775269512** [comment]
model = CatBoostRegressor(
        iterations=1400,
        task_type='GPU', # 'CPU'
        verbose=0,
        loss_function='RMSE',
        #loss_function='Tweedie:variance_power=1.1', grow_policy='Depthwise',
        boosting_type='Plain',
        #depth=8,
        #gpu_cat_features_storage='CpuPinnedMemory',
        #max_ctr_complexity=2,
        #l2_leaf_reg=3
    )

    model.fit(
        train_pool,
        eval_set=val_pool,
        plot=True   
    )
    model_file = 'xxxxxxxxxxxxxxxxx'
    model.save_model(model_file)
    model = CatBoostRegressor().load_model(model_file)
    model.predict(DATA)

**Comment by annaveronika** [comment]
This is now fixed in code, please try building from source. It will be on pypi soon in new minor version of the library.

**Comment by pplonski** [comment]
@annaveronika thank you for the fix! Do you have an estimate when the minor version will be released? I'm working on an autoML package [mljar-supervised](https://github.com/mljar/mljar-supervised). We are using CatBoost among many algorithms, and CatBoost is very often selected as the best algorithm or as a part of the ensemble (which is selected as the best algorithm) and we are waiting for the fix.

**Comment by annaveronika** [comment]
> @annaveronika thank you for the fix! Do you have an estimate when the minor version will be released? I'm working on an autoML package [mljar-supervised](https://github.com/mljar/mljar-supervised). We are using CatBoost among many algorithms, and CatBoost is very often selected as the best algorithm or as a part of the ensemble (which is selected as the best algorithm) and we are waiting for the fix.

In a couple of days

**Comment by Anaststam** [comment]
@annaveronika i still get the same error when saving a model using the save_model function and then trying to load it back by using load_model even though building from source. 

Has anyone else tried again the fix in the code?

**Comment by LyzhinIvan** [comment]
Hi, @Anaststam ! Could you please provide code snippet to reproduce the error?

**Comment by Anaststam** [comment]
`model.fit(train_data, train_labels, cat_features=None, eval_set=None)
 
 model.save_model("{path_to_models}", format="cbm", export_parameters=None, pool=None)
    
 tmodel= model.load_model ({path_to_models}, format="cbm")
    
predictions = tmodel.predict(X_test)`

CatBoostError: Only one of parameters ['verbose', 'logging_level', 'verbose_eval', 'silent'] should be set

**Comment by LyzhinIvan** [comment]
Thanks, @Anaststam ! Yes, it's bug. I'll fix it as soon as possible. Right now you can use CatBoost().load_model to avoid this problem.

**Comment by LyzhinIvan** [comment]
I just realized that I tested your code with old version of catboost. With the latest sources it works correctly. Please try to rebuild catboost from the latest source files.

**Comment by armanhak** [comment]
> Thanks, @Anaststam ! Yes, it's bug. I'll fix it as soon as possible. Right now you can use CatBoost().load_model to avoid this problem.

Thanks, @LyzhinIvan. I had a CatBoostRegressor model and I got the same error when the model loaded CatBoostRegressor․load_model (path) like that. Everything started working without errors when the model was loaded CatBoost.load_model (path) in this way.

**Comment by Anaststam** [comment]
@armanhak LyzhinIvan thanks for your reply. I tried CatBoost.load_model (path) and CatBoost().load_model but i get the following error: 

NameError: name 'CatBoost' is not defined

Could be more specific please?

**Comment by pplonski** [comment]
please import CatBoost

```python
from catboost import CatBoost
```

**Comment by antipisa** [comment]
Hi, has this been fixed yet?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi @antipisa, this issue is not present in 0.24.4 for Linux.

**Comment by antipisa** [comment]
Hi @Evgueni-Petrov-aka-espetrov, but it is present in 0.24.0, correct?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@antipisa, the following example works fine with 0.24.0 and 0.24.4 for Linux
```python
from catboost import CatBoostRegressor
import catboost
print(catboost.__version__)
train_data = [[1, 4, 5, 6],
              [4, 5, 6, 7],
              [30, 40, 50, 60]]
train_labels = [10, 20, 30]
X_test = train_data
model = CatBoostRegressor(loss_function = "RMSE", eval_metric = "RMSE", metric_period = 100, iterations=2000,
                        #use_best_model = True,
                        random_strength = 0.5,
                        learning_rate=0.2,
                        depth=7,
                        random_seed = 93,
                        l2_leaf_reg = 0.1,
                        verbose=False,
                        logging_level = None)
model.fit(train_data, train_labels, cat_features=None, eval_set=None)
model.save_model("model.bin", format="cbm", export_parameters=None, pool=None)
tmodel= model.load_model ("model.bin", format="cbm")
predictions = tmodel.predict(X_test)
```

**Comment by Vivian-nice** [comment]
> > Thanks, @Anaststam ! Yes, it's bug. I'll fix it as soon as possible. Right now you can use CatBoost().load_model to avoid this problem.
> 
> Thanks, @LyzhinIvan. I had a CatBoostRegressor model and I got the same error when the model loaded CatBoostRegressor․load_model (path) like that. Everything started working without errors when the model was loaded CatBoost.load_model (path) in this way.
My job is a regression job,so I do this:
`    from catboost import CatBoost
    model=CatBoost().load_model (MODEL_PATH)
    print("model loaded")`

and get success

**Comment by QuinRiva** [comment]
I get a similar issue with **n_estimators**:
Before saving the model I have the following params:
`{'loss_function': 'RMSE', 'thread_count': 40, 'n_estimators': 1000, 'objective': 'Tweedie:variance_power=1.35'}`

After loading the same model, I have additional params:
`{'loss_function': 'Tweedie:variance_power=1.35', 'thread_count': 40, 'n_estimators': 1000, 'objective': 'Tweedie:variance_power=1.35', 'iterations': 1000, 'verbose': 200, 'use_best_model': True}`
